# Generated by Django 4.2 on 2026-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('newsletter_subscribed', models.BooleanField(default=True, verbose_name='Подписка на рассылку')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=10, verbose_name='Тема')),
                ('courses_completed', models.PositiveIntegerField(default=0, editable=False, verbose_name='Завершено курсов')),
                ('certificates_earned', models.PositiveIntegerField(default=0, editable=False, verbose_name='Сертификатов получено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
