# Generated by Django 4.2 on 2026-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='courses.course', verbose_name='Избранные курсы'),
        ),
    ]
