# Generated by Django 4.2 on 2026-02-24 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержание (Markdown)')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='Ссылка на видео')),
                ('resources', models.TextField(blank=True, default='', verbose_name='Ресурсы (ссылки)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Длительность (минут)')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок в разделе')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный урок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
